---
default: true

# MD010/no-hard-tabs - Hard tabs
MD010:
  # Don't include code blocks, because go.
  code_blocks: false
  # Number of spaces for each hard tab
  spaces_per_tab: 2

# MD013/line-length - Line length
MD013: false

# MD014/commands-show-output - Dollar signs used before commands without output
MD014: false

# MD022/blanks-around-headings/blanks-around-headers
MD022:
  # Blank lines above heading
  lines_above: 1
  # Blank lines below heading
  lines_below: 0

# MD024/no-duplicate-heading/no-duplicate-header
MD024:
  # Only check sibling headings
  siblings_only: true

# MD025/single-title/single-h1 - Multiple top-level headings
MD025: false

# MD026/no-trailing-punctuation - Trailing punctuation in heading
MD026: false

# MD031/blanks-around-fences - Fenced code blocks should be surrounded by blank lines
MD031: false

# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  allowed_elements: []

# MD044/proper-names - Proper names should have the correct capitalization
MD044:
  # List of proper names
  names: []
  # Include code blocks
  code_blocks: true

# MD046/code-block-style - Code block style
MD046:
  # Block style
  style: "fenced"

# MD048/code-fence-style - Code fence style
MD048:
  # Code fence style
  style: "backtick"
